### ISSUE TITLE
FilterOptions are not sorted

### ISSUE THREAD

**Issue by davidmaack** [MetaModels/attribute_country#11]
When using a frontend filter to filter a metamodels using the country attribute, the countries may not sorted, because getFilterOptions() just fetches the tranlsated string without sorting the array afterwards.
getFilterOptions() sould romanize the values first, then sort the array and then get the translated values for the keys, just like Contao is doing it in \System::getCountries()

**Comment by discordier** [comment]
shouold be fixed with 1e5cbb3

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@davidmaack could you please have a final look at this and tell if your issue has been resolved?

**Comment by zonky2** [comment]
@discordier 3 days to test the issue...? may be to fast ;-)

**Comment by discordier** [comment]
Yes, but to be honest, you ARE fast. ;)
Will have a look at it back home.

**Comment by zonky2** [comment]
... o.k., sorry - "time is relative" ;-)

**Comment by discordier** [comment]
It somehow was set to 3 days, it is now on 7 days.
