### ISSUE TITLE
add translation key for "display settings"

### ISSUE THREAD

**Issue by zonky2** [MetaModels/attribute_country#15]
add translation key for "display settings"

![screenshot_358](https://user-images.githubusercontent.com/1045318/51078144-09be4e00-16b1-11e9-8a89-bbeb1e348362.jpg)

**Comment by discordier** [comment]
Metapalette
https://github.com/MetaModels/attribute_country/blob/bc8ee8cde22c1755aef1dbba0b4b553202335a19/src/Resources/contao/dca/tl_metamodel_attribute.php#L25
Does not exist in https://github.com/MetaModels/core/blob/f432690912361eebc4141f1f9397efa8535fe673/contao/dca/tl_metamodel_attribute.php#L213

**Comment by zonky2** [comment]
fixed with https://github.com/MetaModels/core/commit/3749e031a01377ffc0b66ba7a02838a4deb488c4
